package mainPackage;

import java.util.Random;
import java.util.Scanner;

import static java.lang.Math.random;

public class Main {
    static int SIZE = 20;

    public static void main(String[] args){
        int currentIndex = 4;
        Scanner sc = new Scanner(System.in);
        int optionSelected;
        Employee employeeList[] = new Employee[SIZE];
        employeeList[0] = new Employee("Stephen Evern", 4,"05/22/2019", 12.5, 0.2f);
        employeeList[1] = new Employee("Diana Alfonso", 2, "04/02/2016", 0.06f                );
        employeeList[2] = new Employee("Jose Mercado",3, "18/12/2018", 12.5, 0.2f);
        employeeList[3] = new Employee("Jose Ghersy", 1, "05.15.2015", 12.5, 0.2f);

        do {
            optionSelected = displayMainMenu();
            switch (optionSelected){
                case 1:
                    employeeList[currentIndex] = addNewEmployee(currentIndex);
                    currentIndex++;
                    break;
                case 2:
                    displayEmployees(employeeList, currentIndex);
                    break;
                case 3:
                    break;
                case 4:
                    break;
                case 5:
                    break;
                case 6:
                    break;
                default:
                    break;
            }
        }
        while(optionSelected != 0);





    }
    public static void getEmployeeInfo(){
        Scanner sc = new Scanner(System.in);

    }
    public static int displayMainMenu(){
        Scanner sc = new Scanner(System.in);
        int selection;

        System.out.println("Employee.Main Menu\n\n");
        System.out.println("1. Add new Employee");
        System.out.println("2. Display all employees");
        System.out.println("3. Delete employee");
        System.out.println("4. Edit Employee");
        System.out.println("5. Delete an Employee");
        System.out.println("6. Calculate Pay");
        System.out.println("0. to exit the program");
        selection = sc.nextInt();
        return selection;

    }
    public static Employee addNewEmployee(int currentIndex){
        Scanner sc = new Scanner(System.in);
        Employee addingEmployee;
        String firstName, lastName, startDate;
        int employeeID;
        float employeeCommission;
        double employeeHourlyRate;
        System.out.println("First Name:");
        firstName = sc.next();
        System.out.println("Last Name");
        lastName = sc.next();
        currentIndex++;
        employeeID = currentIndex;
        System.out.println("Autogenerated EmployeeId:" + employeeID);
        System.out.println("Start date:");
        startDate = sc.next();
        System.out.println("Employee Hourly Rate:");
        employeeHourlyRate = sc.nextDouble();
        System.out.println("Employee Commission Percentage:");
        employeeCommission = sc.nextFloat();
        String fullName = firstName + " " +lastName;
        addingEmployee = new Employee(fullName, employeeID, startDate, employeeHourlyRate,employeeCommission);
        System.out.println("Employee was successfully created!");
        return addingEmployee;

    }

    public static void displayEmployees(Employee employeeList[], int numberOfEmployees){
        //Scanner sc = new Scanner(System.in);
        for(int x = 0; x < numberOfEmployees; x++){
            System.out.println("Employee Id: "+ employeeList[x].employeeID +
                    " | Employee Name: " + employeeList[x].employeeName +
                    " | Employee Start Date: " + employeeList[x].employeeStartDate +
                    " | Employee Hourly Rate: " + employeeList[x].employeeHourlyRate +
                    " | Employee Commission Percentage: " + employeeList[x].employeeCommissionPercentage);
        }

    }

}
